# Generated by Django 3.2.8 on 2021-12-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spymore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Spy',
        ),
        migrations.DeleteModel(
            name='DriverMore',
        ),
        migrations.DeleteModel(
            name='SpyMore',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
