# Generated by Django 3.2.8 on 2022-01-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_counselors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='counselors',
            new_name='counselor',
        ),
    ]
