# Generated by Django 3.2.8 on 2022-01-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_rename_counselors_counselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
