# Generated by Django 3.2.8 on 2022-01-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_alter_feedback_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholar',
            old_name='income',
            new_name='grno',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='income_p',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='photo',
        ),
        migrations.AddField(
            model_name='scholar',
            name='address',
            field=models.TextField(default='xyz', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='collegename',
            field=models.CharField(default='abc', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='feereceipt',
            field=models.FileField(default='C:\\Aarshiti Group\\website\\media\\schloar_income\\django_cheatsheet.pdf', upload_to='schloar_feereceipt/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='marksheet',
            field=models.FileField(default='C:\\Aarshiti Group\\website\\media\\schloar_income\\django_cheatsheet.pdf', upload_to='schloar_marksheet/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='secemail',
            field=models.EmailField(default='vaishnavi.narkhede20@vit.edu', max_length=254),
            preserve_default=False,
        ),
    ]
