# Generated by Django 3.2.9 on 2022-02-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_auto_20220127_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
