# Generated by Django 4.0.2 on 2022-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0009_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='income',
            field=models.FileField(null=True, upload_to='schloar_income/'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='proof',
            field=models.FileField(null=True, upload_to='schloar_proof/'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='feereceipt',
            field=models.FileField(null=True, upload_to='schloar_feereceipt/'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='marksheet',
            field=models.FileField(null=True, upload_to='schloar_marksheet/'),
        ),
    ]
